# Configuring our pre-commit hooks to be used with https://pre-commit.com/

# ------------------------------------------------------------------------------
# Terramate specific hooks
# ------------------------------------------------------------------------------

- id: terramate-generate
  name: Terramate generate
  description: |
    The terramate generate command is used to generate code from Terramate
    configuration.
  entry: hooks/terramate/generate.sh
  language: script
  pass_filenames: false

- id: terramate-fmt
  name: Terramate fmt
  description: |
    The terramate generate command is used to format Terramate configuration
    code.
  entry: hooks/terramate/fmt.sh
  language: script
  pass_filenames: false

- id: terramate-create
  name: Terramate create
  description: |
    The terramate generate command is used to create Terramate stacks
    code.
  entry: hooks/terramate/create.sh
  language: script
  pass_filenames: false